# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30121
    hostPort: 30121
    protocol: TCP
  - containerPort: 30400
    hostPort: 30400
    protocol: TCP
  - containerPort: 30500
    hostPort: 30500
    protocol: TCP
