apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: openai-gpt4o-mini
  namespace: kagent
spec:
  model: gpt-4o-mini
  provider: OpenAI
  apiKeySecret: openai-secret
  apiKeySecretKey: Authorization
  openAI:
    baseUrl: http://agentgateway-proxy.agentgateway-system.svc.cluster.local/v1
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: openai-gpt4o
  namespace: kagent
spec:
  model: gpt-4o
  provider: OpenAI
  apiKeySecret: openai-secret
  apiKeySecretKey: Authorization
  openAI:
    baseUrl: http://agentgateway-proxy.agentgateway-system.svc.cluster.local/v1
